version: '3.8'
services:
  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3015:3015'
    environment:
      - FIRST_PEER_HASH=http://peer_1:3016
    container_name: client
  bootstrap_node:
    image: bootstrap_node
    build:
      context: ./bootstrapNode
      dockerfile: Dockerfile
    ports:
      - '3010:3010'
    container_name: bootstrap_node
  peer_1:
    image: peer
    build:
      context: ./peer
      dockerfile: Dockerfile
    depends_on:
      - bootstrap_node
    restart: on-failure 
    ports:
      - '3001:3016'
    environment:
      - NODE_ADDRESS=http://peer_1:3016
      - PORT=3016
      - BOOTSTRAP_NODE_ADDRESS=http://bootstrap_node:3010
      - QRNG_GET_RANDOM_ARRAY_URL=https://qrng.qbck.io
      - QRNG_GET_RANDOM_ARRAY_API_KEY=9627fecf-f335-41b3-9560-82875c80afe9
    container_name: peer_1
  peer_2:
    image: peer
    ports:
      - '3003:3016'
    depends_on:
      - bootstrap_node
      - peer_1
    restart: on-failure 
    environment:
      - NODE_ADDRESS=http://peer_2:3016
      - PORT=3016
      - BOOTSTRAP_NODE_ADDRESS=http://bootstrap_node:3010
      - QRNG_GET_RANDOM_ARRAY_URL=https://qrng.qbck.io
      - QRNG_GET_RANDOM_ARRAY_API_KEY=9627fecf-f335-41b3-9560-82875c80afe9
    container_name: peer_2
  peer_3:
    image: peer
    ports:
      - '3005:3016'
    depends_on:
      - bootstrap_node
      - peer_1
      - peer_2
    restart: on-failure 
    environment:
      - NODE_ADDRESS=http://peer_3:3016
      - PORT=3016
      - BOOTSTRAP_NODE_ADDRESS=http://bootstrap_node:3010
      - QRNG_GET_RANDOM_ARRAY_URL=https://qrng.qbck.io
      - QRNG_GET_RANDOM_ARRAY_API_KEY=9627fecf-f335-41b3-9560-82875c80afe9
    container_name: peer_3
  peer_4:
    image: peer
    ports:
      - '3007:3016'
    depends_on:
      - bootstrap_node
      - peer_1
      - peer_2
      - peer_3
    restart: on-failure 
    environment:
      - NODE_ADDRESS=http://peer_4:3016
      - PORT=3016
      - BOOTSTRAP_NODE_ADDRESS=http://bootstrap_node:3010
      - QRNG_GET_RANDOM_ARRAY_URL=https://qrng.qbck.io
      - QRNG_GET_RANDOM_ARRAY_API_KEY=9627fecf-f335-41b3-9560-82875c80afe9
    container_name: peer_4
